name: Arduino Library

on:
  pull_request:
    branches:
      - main

jobs:
  Arduino-Checks:
    uses: sensirion/.github/.github/workflows/upt.arduino.check.yml@main
    with:
      expect-arduino-examples: true
      lint-lib-manager-check: update
      dependency-list: "[{'name': 'Sensirion UPT Core', 'version': '0.9.4'}, {'name': 'NimBLE-Arduino', version: '2.3.6'},  {'source-path': './'}]"
